blog_home:
    path:     /
    defaults: { _controller: BlogBundle:page }
    requirements:
             methods:  GET
blog_about:
    path:   /about
    defaults: { _controller: BlogBundle:page }
    requirements:
         methods:  GET

blog_contact:
    path:   /contact
    defaults: { _controller: BlogBundle:page }
    requirements:
         methods:  GET|POST
blog_show:
    path:  /show{id}
    defaults: { _controller: BlogBundle:Blog }
    requirements:
        methods:  GET
        id: \d+

blog_post:
    path: /post
    defaults: { _controller: BlogBundle:post }

blog_index:
    path: /start
    defaults: { _controller: BlogBundle:index }

